# Generated by Django 5.1.4 on 2024-12-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureTwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureItemLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('featureIcon', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
            },
        ),
    ]
